import { ClassSpellGroups } from "../enums/spellSchools";

export interface IClassSpells {
    classSpellGroup: ClassSpellGroups;
    spellIds: string[];
}

export const ClassSpellList: IClassSpells[] = [
    {
        classSpellGroup: ClassSpellGroups.BARD,
        spellIds: [
            // Cantrips
            'BLADE_WARD', 'DANCING_LIGHTS', 'FRIENDS', 'LIGHT', 'MAGE_HAND', 'MENDING', 'MESSAGE', 'MINOR_ILLUSION', 'PRESTIDIGITATION', 'TRUE_STRIKE', 'VICIOUS_MOCKERY',
            // L1
            'ANIMAL_FRIENDSHIP', 'BANE', 'CHARM_PERSON', 'COMPREHEND_LANGUAGES', 'CURE_WOUNDS', 'DETECT_MAGIC', 'DISGUISE_SELF', 'DISSONANT_WHISPERS', 'FAERIE_FIRE',
            'HEALING_WORD', 'HEROISM', 'IDENTIFY', 'ILLUSORY_SCRIPT', 'LONGSTRIDER', 'SILENT_IMAGE', 'SLEEP', 'SPEAK_WITH_ANIMALS', 'TASHA\'S_HIDEOUS_LAUGHTER', 'THUNDERWAVE',
            'UNSEEN_SERVANT',
            // L2
            'ANIMAL_MESSENGER', 'BLINDNESS/DEAFNESS', 'CALM_EMOTIONS', 'CLOUD_OF_DAGGERS', 'CROWN_OF_MADNESS', 'DETECT_THOUGHTS', 'ENHANCE_ABILITY', 'ENTHRALL', 'HEAT_METAL',
            'HOLD_PERSON', 'INVISIBILITY', 'KNOCK', 'LESSER_RESTORATION', 'LOCATE_ANIMALS_OR_PLANTS', 'LOCATE_OBJECT', 'MAGIC_MOUTH', 'PHANTASMAL_FORCE', 'SEE_INVISIBILITY',
            'SHATTER', 'SILENCE', 'SUGGESTION', 'ZONE_OF_TRUTH',
            // L3
            'BESTOW_CURSE', 'CLAIRVOYANCE', 'DISPEL_MAGIC', 'FEAR', 'FEIGN_DEATH', 'GLYPH_OF_WARDING', 'HYPNOTIC_PATTERN', 'LEOMUND\'S_TINY_HUT', 'MAJOR_IMAGE', 'NONDETECTION',
            'PLANT_GROWTH', 'SENDING', 'SPEAK_WITH_DEAD', 'SPEAK_WITH_PLANTS', 'STINKING_CLOUD', 'TONGUES',
            // L4
            'COMPULSION', 'CONFUSION', 'DIMENSION_DOOR', 'FREEDOM_OF_MOVEMENT', 'GREATER_INVISIBILITY', 'HALLUCINATORY_TERRAIN', 'LOCATE_CREATURE', 'POLYMORPH',
            // L5
            'ANIMATE_OBJECTS', 'AWAKEN', 'DOMINATE_PERSON', 'DREAM', 'GEAS', 'GREATER_RESTORATION', 'HOLD_MONSTER', 'LEGEND_LORE', 'MASS_CURE_WOUNDS', 'MISLEAD', 'MODIFY_MEMORY',
            'PLANAR_BINDING', 'RAISE_DEAD', 'SCRYING', 'SEEMING', 'TELEPORTATION_CIRCLE',
            // L6
            'EYEBITE', 'FIND_THE_PATH', 'GUARDS_AND_WARDS', 'MASS_SUGGESTION', 'OTTO\'S_IRRESISTIBLE_DANCE', 'PROGRAMMED_ILLUSION', 'TRUE_SEEING',
            // L7
            'ETHEREALNESS', 'FORCECAGE', 'MIRAGE_ARCANE', 'MORDENKAINEN\'S_MAGNIFICENT_MANSION', 'MORDENKAINEN\'S_SWORD', 'PROJECT_IMAGE', 'REGENERATE', 'RESURRECTION', 'SYMBOL',
            'TELEPORT',
            // L8
            'DOMINATE_MONSTER', 'FEEBLEMIND', 'GLIBNESS', 'MIND_BLANK', 'POWER_WORD_STUN',
            // L9
            'FORESIGHT', 'POWER_WORD_HEAL', 'POWER_WORD_KILL', 'TRUE_POLYMORPH',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.CLERIC,
        spellIds: [
            // Cantrips
            'GUIDANCE', 'LIGHT', 'MENDING', 'RESISTANCE', 'SACRED_FLAME', 'SPARE_THE_DYING', 'THAUMATURGY',
            // L1
            'BANE', 'BLESS', 'COMMAND', 'CREATE_OR_DESTROY_WATER', 'CURE_WOUNDS', 'DETECT_EVIL_AND_GOOD', 'DETECT_MAGIC', 'DETECT_POISON_AND_DISEASE', 'GUIDING_BOLT', 'HEALING_WORD',
            'INFLICT_WOUNDS', 'PROTECTION_FROM_EVIL_AND_gOOD', 'PURIFY_FOOD_AND_DRINK', 'SANTUARY', 'SHIELD_OF_FAITH',
            // L2
            'AID', 'AUGURY', 'BLINDNESS/DEAFNESS', 'CALM_EMOTIONS', 'CONTINUAL_FLAME', 'ENHANCE_ABILITY', 'FIND_TRAPS', 'GENTLE_REPOSE', 'HOLD_PERSON', 'LESSER_RESTORATION',
            'LOCATE_OBJECT', 'PRAYER_OF_HEALING', 'PROTECTION_FROM_POISON', 'SILENCE', 'SPIRITUAL_WEAPON', 'WARDING_BOND', 'ZONE_OF_TRUTH',
            // L3
            'ANIMATE_DEAD', 'BEACON_OF_HOPE', 'BESTOW_CURSE', 'CLAIRVOYANCE', 'CREATE_FOOD_AND_WATER', 'DAYLIGHT', 'DISPEL_MAGIC', 'FEIGN_DEATH', 'GLYPH_OF_WARDING', 'MAGIC_CIRCLE',
            'MASS_HEALING_WORD', 'MELD_INTO_STONE', 'PROTECTION_FROM_ENERGY', 'REMOVE_CURSE', 'REVIVIFY', 'SENDING', 'SPEAK_WITH_DEAD', 'SPIRIT_GAURDIANS', 'TONGUES', 'WATER_WALK',
            // L4
            'BANISHMENT', 'CONTROL_WATER', 'DEATH_WARD', 'DIVINATION','FREEDOM_OF_MOVEMENT', 'GUARDIAN_OF_FAITH', 'LOCATE_CREATURE', 'STONE_SHAPE',
            // L5
            'COMMUNE', 'CONTAGION', 'DISPEL_EVIL_AND_GOOD', 'FLAME_STRIKE', 'GEAS', 'GREATER_RESTORATION', 'HALLOW', 'INSECT_PLAGUE', 'LEGEND_LORE', 'MASS_CURE_WOUNDS',
            'PLANAR_BINDING', 'RAISE_DEAD', 'SCRYING',
            // L6
            'BLADE_BARRIER', 'CREATE_UNDEAD', 'FIND_THE_PATH', 'FORBIDDANCE', 'HARM', 'HEAL', 'HEROES\'_FEAST', 'PLANAR_ALLY', 'TRUE_SEEING', 'WORD_OF_RECALL',
            // L7
            'CONJURE_CELESTIAL', 'DIVINE_WORD', 'ETHEREALNESS', 'FIRE_STORM', 'PLANE_SHIFT', 'REGENERATE', 'RESURRECTION', 'SYMBOL',
            // L8
            'ANTIMAGIC_FIELD', 'CONTROL_WEATHER', 'EARTHQUAKE', 'HOLY_AURA',
            // L9
            'ASTRAL_PROJECTION', 'GATE', 'MASS_HEAL', 'TRUE_RESURRECTION',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.DRUID,
        spellIds: [
            // Cantrips
            'DRUIDCRAFT', 'GUIDANCE', 'MENDING', 'POISON_SPRAY', 'PRODUCE_FLAME', 'RESISTANCE', 'SHILLELAGH', 'THRON_WHIP',
            // L1
            'ANIMAL_FRIENDSHIP', 'CHARM_PERSON', 'CREATE_OR_DESTROY_WATER', 'CURE_WOUNDS', 'DETECT_MAGIC', 'DETECT_POISON_AND_DISEASE', 'ENTANGLE', 'FAERIE_FIRE', 'FOG_CLOUD',
            'GOODBERRY', 'HEALING_WORD', 'JUMP', 'LONGSTRIDER', 'PURIFY_FOOD_AND_DRINK', 'SPEAK_WITH_ANIMALS', 'THUNDERWAVE',
            // L2
            'ANIMAL_MESSENGER', 'BARKSKIN', 'BEAST_SENSE', 'DARKVISION', 'ENHANCE_ABILITY', 'FIND_TRAPS', 'FLAME_BLADE', 'FLAMING_SPHERE', 'GUST_OF_WIND', 'HEAT_METAL', 'HOLD_PERSON',
            'LESSER_RESTORATION', 'LOCATE_ANIMALS_OR_PLANTS', 'LOCATE_OBJECT', 'MOONBEAM', 'PASS_WITHOUT_TRACE', 'PROECTION_FROM_POISON', 'SPIKE_GROWTH',
            // L3
            'CALL_LIGHTNING', 'CONJURE_ANIMALS', 'DAYLIGHT', 'DISPEL_MAGIC', 'FEIGN_DEATH', 'MELD_INTO_STONE', 'PLANT_GROWTH', 'PROTECTION_FROM_ENERGY', 'SLEET_STORM',
            'SPEAK_WITH_PLANTS', 'WATER_BREATHING', 'WATER_WALK', 'WIND_WALL',
            // L4
            'BLIGHT', 'CONFUSION', 'CONJURE_MINOR_ELEMENTALS', 'CONJURE_WOODLAND_BEINGS', 'CONTROL_WATER', 'FREEDOM_OF_MOVEMENT', 'GIANT_INSECT', 'GRASPING_VINE',
            'HALLUCINATORY_TERRAIN', 'ICE_STORM', 'LOCATE_CREATURE', 'POLYMORPH', 'STONE_SHAPE', 'STONESKIN', 'WALL_OF_FIRE',
            // L5
            'ANTILIFE_SHELL', 'AWAKEN', 'COMMUNTE_WITH_NATURE', 'CONJURE_ELEMENTAL', 'CONTAGION', 'GEAS', 'GREATER_RESTORATION', 'INSECT_PLAGUE', 'MASS_CURE_WOUNDS',
            'PLANAR_BINDING', 'REINCARNATE', 'SCRYING', 'TREE_STRIDE', 'WALL_OF_STONE',
            // L6
            'CONJURE_FEY', 'FIND_THE_PATH', 'HEAL', 'HEROES\'_FEAST', 'MOVE_EARTH', 'SUNBEAM', 'TRANSPORT_VIA_PLANTS', 'WALL_OF_THORNS', 'WIND_WALK',
            // L7
            'FIRE_STORM', 'MIRAGE_ARCANE', 'PLANE_SHIFT', 'REGENERATE', 'REVERSE_GRAVITY',
            // L8
            'ANIMAL_SHAPES', 'ANTIPATHY/SYMPATHY', 'CONTROL_WEATHER', 'EARTHQUAKE', 'FEEBLEMIND', 'SUNBURST', 'TSUNAMI',
            // L9
            'FORESIGHT', 'SHAPECHANGE', 'STORM_OF_VENGEANCE', 'TRUE_RESURRECTION',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.PALADIN,
        spellIds: [
            // L1
            'BLESS', 'COMMAND', 'COMPELLED_DUEL', 'CURE_WOUNDS', 'DETECT_EVIL_AND_GOOD', 'DETECT_MAGIC', 'DETECT_POISON_AND_DISEASE', 'DIVINE_FAVOR', 'HEROISM',
            'PROTECTION_FROM_EVIL_AND_GOOD', 'PURIFY_FOOD_AND_DRINK', 'SEARING_SMITE', 'SHIELD_OF_FAITH', 'THUNDEROUS_SMITE', 'WRATHFUL_SMITE',
            // L2
            'AID', 'BRANDING_SMITE', 'FIRE_STEED', 'LESSER_RESTORATION', 'LOCATE_OBJECT', 'MAGIC_WEAPON', 'PROTECTION_FROM_POISON', 'ZONE_OF_TRUTH',
            // L3
            'AURA_OF_VITALITY', 'BLINDING_SMITE', 'CREATE_FOOD_AND_WATER', 'CRUSADER\'S_MANTLE', 'DAYLIGHT', 'DISPEL_MAGIC', 'ELEMENTAL_WEAPON', 'MAGIC_CIRCLE',
            'REMOVE_CURSE', 'REVIVIFY',
            // L4
            'AURA_OF_LIFE', 'AURA_OF_PURITY', 'BANISHMENT', 'DEATH_WARD', 'LOCATE_CREATURE', 'STAGGERING_SMITE',
            // L5
            'BANISHING_SMITE', 'CIRCLE_OF_POWER', 'DESTRUCTIVE_WAVE', 'DISPEL_EVIL_AND_GOOD', 'GEAS', 'RAISE_DEAD',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.RANGER,
        spellIds: [
            // L1
            'ALARM', 'ANIMAL_FRIENDSHIP', 'CURE_WOUNDS', 'DETECT_MAGIC', 'DETECT_POISON_AND_DISEASE', 'ENSNARING_STRIKE', 'FOG_CLOUD', 'GOODBERRY', 'HAIL_OF_THORNS',
            'HUNTER\S_MARK', 'JUMP', 'LONGSTRIDER', 'SPEAK_WITH_ANIMALS',
            // L2
            'ANIMAL_MESSENGER', 'BARKSKIN', 'BEAST_SENSE', 'CORDON_OF_ARROWS', 'DARKVISION', 'FIND_TRAPS', 'LESSER_RESTORATION', 'LOCATE_ANIMALS_OR_PLANTS',
            'LOCATE_OBJECT', 'PASS_WITHOUT_TRACE', 'PROTECTION_FROM_POISON', 'SILENCE', 'SPIKE_GROWTH',
            // L3
            'CONJURE_ANIMALS', 'CONJURE_BARRAGE', 'DAYLIGHT', 'LIGHTNING_ARROW', 'NONDETECTION', 'PLANT_GROWTH', 'PROTECTION_FROM_ENERGY', 'SPEAK_WITH_PLANTS',
            'WATER_BREATHING', 'WATER_WALK', 'WIND_WALL',
            // L4
            'CONJURE_WOODLAND_BEINGS', 'FREEDOM_OF_MOVEMENT', 'GRASPING_VINE', 'LOCATE_CREATURE', 'STONESKIN',
            // L5
            'COMMUNE_WITH_NATURE', 'CONJURE_VOLLEY', 'SWIFT_QUIVER', 'TREE_STRIDE',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.SORCERER,
        spellIds: [
            // Cantrips
            'ACID_SPLASH', 'BLADE_WARD', 'CHILL_TOUCH', 'DANCING_LIGHTS', 'FIRE_BOLT', 'FRIENDS', 'LIGHT', 'MAGE_HAND', 'MENDING', 'MESSAGE', 'MINOR_ILLUSION', 'POISON_SPRAY',
            'PRESTIDIGITATION', 'RAY_OF_FROST', 'SHOCKING_GRASP', 'TRUE_STRIKE',
            // L1
            'BURNING_HANDS', 'CHARM_PERSON', 'CHROMATIC_ORB', 'COLOR_SPRAY', 'COMPREHEND_LANGUAGES', 'DETECT_MAGIC', 'DISGUISE_SELF', 'EXPEDITIOUS_RETREAT', 'FALSE_LIFE',
            'FEATHER_FALL', 'FOG_CLOUD', 'JUMP', 'MAGE_ARMOR', 'MAGIC_MISSILE', 'RAY_OF_SICKNESS', 'SHIELD', 'SILENT_IMAGE', 'SLEEP', 'THUNDERWAVE', 'WITCH_BOLT',
            // L2
            'ALTER_SELF', 'BLINDNESS/DEAFNESS', 'BLUR', 'CLOUD_OF_DAGGERS', 'CROWN_OF_MADNESS', 'DARKNESS', 'DARKVISION', 'DETECT_THOUGHTS', 'ENHANCE_ABILITY', 'ENLARGE/REDUCE',
            'GUST_OF_WIND', 'HOLD_PERSON', 'INVISIBILITY', 'KNOCK', 'LEVITATE', 'MIRROR_IMAGE', 'MISTY_STEP', 'PHANTASMAL_FORCE', 'SORCHING_RAY', 'SEE_INVISIBILITY', 'SHATTER',
            'SPIDER_CLIMB', 'SUGGESTION', 'WEB',
            // L3
            'BLINK', 'CLAIRVOYANCE', 'COUNTERSPELL', 'DAYLIGHT', 'DISPEL_MAGIC', 'FEAR', 'FIREBALL', 'FLY', 'GASEOUS_FORM', 'HASTE', 'HYPNOTIC_PATTERN', 'LIGHTNING_BOLT',
            'MAJOR_IMAGE', 'PROTECTION_FROM_ENERGY', 'SLEET_STORM', 'SLOW', 'STINKING_CLOUD', 'TONGUES', 'WATER_BREATHING', 'WATER_WALK',
            // L4
            'BANISHMENT', 'BLIGHT', 'CONFUSION', 'DIMENSION_DOOR', 'DOMINATE_BEAST', 'GREATER_INVISIBILITY', 'ICE_STORM', 'POLYMORPH', 'STONESKIN', 'WALL_OF_FIRE',
            // L5
            'ANIMATE_OBJECTS', 'CLOUDKILL', 'CONE_OF_COLD', 'CREATION', 'DOMINATE_PERSON', 'HOLD_MONSTER', 'INSECT_PLAGUE', 'SEEMING', 'TELEKINESIS', 'TELEPORTATION_CIRCLE',
            'WALL_OF_STONE',
            // L6
            'ARCANE_GATE', 'CHAIN_LIGHTNING', 'CIRCLE_OF_DEATH', 'DISINTEGRATE', 'EYEBITE', 'GLOBE_OF_INVULNERABILITY', 'MASS_SUGGESTION', 'MOVE_EARTH', 'SUNBEAM', 'TRUE_SEEING',
            // L7
            'DELAYED_BLAST_FIREBALL', 'ETHEREALNESS', 'FINGER_OF_DEATH', 'FIRE_STORM', 'PLANE_SHIFT', 'PRISMATIC_SPRAY', 'REVERSE_GRAVITY', 'TELEPORT',
            // L8
            'DOMINATE_MONSTER', 'EARTHQUAKE', 'INCENDIARY_CLOUD', 'POWER_WORD_STUN', 'SUNBURST',
            // L9
            'GATE', 'METEOR_SWARM', 'POWER_WORD_KILL', 'TIME_STOP', 'WISH',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.WARLOCK,
        spellIds: [
            // Cantrips
            'BLADE_WARD', 'CHILL_TOUCH', 'ELDRITCH_BLAST', 'FRIENDS', 'MAGE_HAND', 'MINOR_ILLUSION', 'POISON_SPRAY', 'PRESTIDIGITATION', 'TRUE_STRIKE',
            // L1
            'ARMOR_OF_AGATHYS', 'ARMS_OF_HADAR', 'CHARM_PERSON', 'COMPREHEND_LANGUAGES', 'EXPEDITIOUS_RETREAT', 'HELLISH_REBUKE', 'HEX', 'ILLUSIORY_SCRIPT',
            'PROTECTION_FROM_EVIL_AND_GOOD', 'UNSEEN_SERVANT', 'WITCH_BOLT',
            // L2
            'CLOUD_OF_DAGGERS', 'CROWN_OF_MADNESS', 'DARKNESS', 'ENTHRALL', 'HOLD_PERSON', 'INVISIBILITY', 'MIRROR_IMAGE', 'MISTY_STEP', 'RAY_OF_ENFEEBLEMENT', 'SHATTER',
            'SPIDER_CLIMB', 'SUGGESTION',
            // L3
            'COUNTERSPELL', 'DISPEL_MAGIC', 'FEAR', 'FLY', 'GASEOUS_FORM', 'HUNGER_OF_HADAR', 'HYPNOTIC_PATTERN', 'MAGIC_CIRCLE', 'MAJOR_IMAGE', 'REMOVE_CURSE', 'TONGUES',
            'VAMPIRIC_TOUCH',
            // L4
            'BANISHMENT', 'BLIGHT', 'DIMENSION_DOOR', 'HALLUCINATORY_TERRAIN',
            // L5
            'CONTACT_OTHER_PLANE', 'DREAM', 'HOLD_MONSTER', 'SCRYING',
            // L6
            'ARCANE_GATE', 'CIRCLE_OF_DEATH', 'CONJURE_FEY', 'CREATE_UNDEAD', 'EYEBITE', 'FLESH_TO_STONE', 'MASS_SUGGESTION', 'TRUE_SEEING',
            // L7
            'ETHEREALNESS', 'FINGER_OF_DEATH', 'FORCECAGE', 'PLANE_SHIFT',
            // L8
            'DEMIPLANE', 'DOMINATE_MONSTER', 'FEEBLEMIND', 'GLIBNESS', 'POWER_WORD_STUN',
            // L9
            'ASTRAL_PROJECTION', 'FORESIGHT', 'IMPRISONMENT', 'POWER_WORD_KILL', 'TRUE_POLYMORPH',
        ]
    },
    {
        classSpellGroup: ClassSpellGroups.WIZARD,
        spellIds: [
            // Cantrips
            'ACID_SPLASH', 'BLADE_WARD', 'CHILL_TOUCH', 'DANCING_LIGHTS', 'FIRE_BOLT', 'FRIENDS', 'LIGHT', 'MAGE_HAND', 'MENDING', 'MESSAGE', 'MINOR_ILLUSION',
            'POISON_SPRAY', 'PRESTIDIGITATION', 'RAY_OF_FROST', 'SHOCKING_GRASP', 'TRUE_STRIKE',
            // L1
            'ALARM', 'BURNING_HANDS', 'CHARM_PERSON', 'CHROMATIC_ORB', 'COLOR_SPRAY', 'COMPREHEND_LANGUAGES', 'DETECT_MAGIC', 'DISGUISE_SELF', 'EXPEDITIOUS_RETREAT',
            'FALSE_LIFE', 'FEATHER_FALL', 'FIND_FAMILIAR', 'FOG_CLOUD', 'GREASE', 'IDENTIFY', 'ILLUSORY_SCRIPT', 'JUMP', 'LONGSTRIDER', 'MAGE_ARMOR', 'MAGIC_MISSILE',
            'PROTECTION_FROM_EVIL_AND_GOOD', 'RAY_OF_SICKNESS', 'SHIELD', 'SILENT_IMAGE', 'SLEEP', 'TASHA\'S_HIDEOUS_LAUGHTER', 'TENSER\'S_FLOATING_DISK', 'THUNDERWAVE',
            'UNSEEN_SERVANT', 'WITCH_BOLT',
            // L2
            'ALTER_SELF', 'ARCANE_LOCK', 'BLINDNESS/DEAFNESS', 'BLUR', 'CLOUD_OF_DAGGERS', 'CONTINUAL_FLAME', 'CROWN_OF_MADDNESS', 'DARKNESS', 'DARKVISION', 'DETECT_THOUGHTS',
            'ENLARGE/REDUCE', 'FLAMING_SPHERE', 'GENTLE_REPOSE', 'GUST_OF_WIND', 'HOLD_PERSON', 'INVISIBILITY', 'KNOCK', 'LEVITATE', 'LOCATE_OBJECT', 'MAGIC_MOUTH',
            'MAGIC_WEAPON', 'MELF\'S_ACID_ARROW', 'MIRROR_IMAGE', 'MISTY_STEP', 'NYSTUL\'S_MAGIC_AURA', 'PHANTASMAL_FORCE', 'RAY_OF_ENFEEBLEMENT', 'ROPE_TRICK',
            'SCORCHING_RAY', 'SEE_INVISIBILITY', 'SHATTER', 'SPIDER_CLIMB', 'SUGGESTION', 'WEB',
            // L3
            'ANIMATE_DEAD', 'BESTOW_CURSE', 'BLINK', 'CLAIRVOYANCE', 'DISPEL_MAGIC', 'FEAR', 'FEIGN_DEATH', 'FIREBALL', 'FLY', 'GASEOUS_FORM', 'GLYPH_OF_WARDING', 'HASTE',
            'HYPNOTIC_PATTERN', 'LEOMUND\'S_TINY_HUT', 'LIGHTNING_BOLT', 'MAGIC_CIRCLE', 'MAJOR_IMAGE', 'NONDETECTION', 'PHANTOM_STEED', 'PROTECTION_FROM_ENERGY',
            'REMOVE_CURSE', 'SENDING', 'SLEET_STORM', 'SLOW', 'STINKING_CLOUD', 'TONGUES', 'VAMPIRIC_TOUCH', 'WATER_BREATHING',
            // L4
            'ARCANE_EYE', 'BANISHMENT', 'BLIGHT', 'CONFUSION', 'CONJURE_MINOR_ELEMENTALS', 'CONTROL_WATER', 'DIMENSION_DOOR', 'EVARD\'S_BLACK_TENTACLES', 'FABRICATE',
            'FIRE_SHIELD', 'GREATER_INVISIBILITY', 'HALLUCINATORY_TERRAIN', 'ICE_STORM', 'LEOMUND\'S_SECRET_CHEST', 'LOCATE_CREATURE', 'MORDENKAINEN\'S_FAITHFUL_HOUND',
            'MORDENKAINEN\'S_PRIVATE_SANCTUM', 'OTILUKE\'S_RESILIENT_SPHERE', 'PHANTASMAL_KILLER', 'POLYMORPH', 'STONE_SHAPE', 'STONESKIN', 'WALL_OF_FIRE',
            // L5
            'ANIMATE_OBJECTS', 'BIGBY\'S_HAND', 'CLOUDKILL', 'CONE_OF_COLD', 'CONJURE_ELEMENTAL', 'CONTACT_OTHER_PLANE', 'CREATION', 'DOMINATE_PERSON', 'DREAM', 'GEAS',
            'HOLD_MONSTER', 'LEGEND_LORE', 'MISLEAD', 'MODIFY_MEMORY', 'PASSWALL', 'PLANAR_BINDING', 'RARY\'S_TELEPATHIC_BOND', 'SCRYING', 'SEEMING', 'TELEKINESIS',
            'TELEPORTATION_CIRCLE', 'WALL_OF_FORCE', 'WALL_OF_STONE',
            // L6
            'ARCANE_GATE', 'CHAIN_LIGHTNING', 'CIRCLE_OF_DEATH', 'CONTINGENCY', 'CREATE_UNDEAD', 'DISINTEGRATE', 'DRAWMIJ\'S_INSTANT_SUMMONS', 'EYEBITE', 'FLESH_TO_STONE',
            'GLOBE_OF_INVULNERABILITY', 'GUARDS_AND_WARDS', 'MAGIC_JAR', 'MASS_SUGGESTION', 'MOVE_EARTH', 'OTILUKE\'S_FREEZING_SPHERE', 'OTTO\'S_IRRESISTIBLE_DANCE',
            'PROGRAMMED_ILLUSION', 'SUNBEAM', 'TRUE_SEEING', 'WALL_OF_ICE',
            // L7
            'DELAYED_BLAST_FIREBALL', 'ETHEREALNESS', 'FINGER_OF_DEATH', 'FORCE_CAGE', 'MIREAGE_ARCANE', 'MORDENKAINEN\'S_MAGNIFICENT_MANSION', 'MORDENKAINEN\'S_SWORD',
            'PLANE_SHIFT', 'PRISMATIC_SPRAY', 'PROJECT_IMAGE', 'REVERSE_GRAVITY', 'SEQUESTER', 'SIMALCRUM', 'SYMBOL', 'TELEPORT',
            // L8
            'ANTIMAGIC FIELD', 'ANTIPATHY/SYMPATHY', 'CLONE', 'CONTROL_WEATHER', 'DEMIPLANE', 'DOMINATE_MONSTER', 'FEEBLEMIND', 'INCENDIARY_CLOUD', 'MAZE', 'MIND_BLANK',
            'POWER_WORD_STUN', 'SUNBURST', 'TELEPATHY',
            // L9
            'ASTRAL_PROJECTION', 'FORESIGHT', 'GATE', 'IMPRISONMENT', 'METEOR_SWARM', 'POWER_WORD_KILL', 'PRISMATIC_WALL', 'SHAPECHANGE', 'TIME_STOP', 'TRUE_POLYMORPH',
            'WEIRD', 'WISH',
        ]
    }
]